ALTER TABLE gestion_metricas
    ADD COLUMN IF NOT EXISTS fb_me_gusta INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fb_me_encanta INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fb_me_entristece INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fb_me_sorprende INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fb_me_enoja INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fb_me_importa INTEGER NOT NULL DEFAULT 0;